//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackOfficeTree
    {
        public int ID { get; set; }
        public string EnglishName { get; set; }
        public string ArabicName { get; set; }
        public string FormName { get; set; }
        public Nullable<int> Perantid { get; set; }
        public Nullable<int> imgIndex { get; set; }
        public Nullable<int> Sortid { get; set; }
    }
}
