//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class LKUPMainTree
    {
        public int ID { get; set; }
        public string FormID { get; set; }
        public string CaptionEn { get; set; }
        public string CaptionAr { get; set; }
        public string Perant_FormID { get; set; }
        public string FormName { get; set; }
        public string Function { get; set; }
        public Nullable<int> Icon { get; set; }
        public Nullable<double> indexSort { get; set; }
        public Nullable<bool> IsUserControl { get; set; }
    }
}
