//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBEntities : DbContext
    {
        public DBEntities()
            : base("name=DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BackOfficeTree> BackOfficeTrees { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<GroupPermission> GroupPermissions { get; set; }
        public virtual DbSet<LKUPPhoneType> LKUPPhoneTypes { get; set; }
        public virtual DbSet<POS_Area> POS_Area { get; set; }
        public virtual DbSet<POS_Attributes> POS_Attributes { get; set; }
        public virtual DbSet<POS_Customers> POS_Customers { get; set; }
        public virtual DbSet<POS_CustomersAddress> POS_CustomersAddress { get; set; }
        public virtual DbSet<POS_CustomerServicePrice> POS_CustomerServicePrice { get; set; }
        public virtual DbSet<POS_CustomersTel> POS_CustomersTel { get; set; }
        public virtual DbSet<POS_Expenses> POS_Expenses { get; set; }
        public virtual DbSet<POS_ExpensesTypes> POS_ExpensesTypes { get; set; }
        public virtual DbSet<POS_Floors> POS_Floors { get; set; }
        public virtual DbSet<POS_Items> POS_Items { get; set; }
        public virtual DbSet<POS_ItemsCategories> POS_ItemsCategories { get; set; }
        public virtual DbSet<POS_Kitchens> POS_Kitchens { get; set; }
        public virtual DbSet<POS_LKUPOrderType> POS_LKUPOrderType { get; set; }
        public virtual DbSet<POS_Orders2> POS_Orders2 { get; set; }
        public virtual DbSet<POS_ShiftsTransaction> POS_ShiftsTransaction { get; set; }
        public virtual DbSet<POS_ShiftsTransaction2> POS_ShiftsTransaction2 { get; set; }
        public virtual DbSet<POS_ShifTypes> POS_ShifTypes { get; set; }
        public virtual DbSet<POS_Sizes> POS_Sizes { get; set; }
        public virtual DbSet<POS_Tables> POS_Tables { get; set; }
        public virtual DbSet<ScreensPermission> ScreensPermissions { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersPermission> UsersPermissions { get; set; }
        public virtual DbSet<POS_ItemsSizes> POS_ItemsSizes { get; set; }
        public virtual DbSet<LKUPCounty> LKUPCounties { get; set; }
        public virtual DbSet<LKUPMainTree> LKUPMainTrees { get; set; }
        public virtual DbSet<POS_Orders> POS_Orders { get; set; }
    
        public virtual int AssignOrdersToCurrentShift(Nullable<long> shift_ID, Nullable<long> p_Branch_ID)
        {
            var shift_IDParameter = shift_ID.HasValue ?
                new ObjectParameter("Shift_ID", shift_ID) :
                new ObjectParameter("Shift_ID", typeof(long));
    
            var p_Branch_IDParameter = p_Branch_ID.HasValue ?
                new ObjectParameter("p_Branch_ID", p_Branch_ID) :
                new ObjectParameter("p_Branch_ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AssignOrdersToCurrentShift", shift_IDParameter, p_Branch_IDParameter);
        }
    
        public virtual int POS_CustomerDeltails_save(Nullable<long> customerID, string branch_ID, string xML)
        {
            var customerIDParameter = customerID.HasValue ?
                new ObjectParameter("CustomerID", customerID) :
                new ObjectParameter("CustomerID", typeof(long));
    
            var branch_IDParameter = branch_ID != null ?
                new ObjectParameter("Branch_ID", branch_ID) :
                new ObjectParameter("Branch_ID", typeof(string));
    
            var xMLParameter = xML != null ?
                new ObjectParameter("XML", xML) :
                new ObjectParameter("XML", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POS_CustomerDeltails_save", customerIDParameter, branch_IDParameter, xMLParameter);
        }
    
        public virtual ObjectResult<POS_getAllItems_Result> POS_getAllItems()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<POS_getAllItems_Result>("POS_getAllItems");
        }
    
        public virtual int POS_OrdersDeltails_save(string xML, Nullable<long> master_ID, Nullable<long> branch_ID)
        {
            var xMLParameter = xML != null ?
                new ObjectParameter("XML", xML) :
                new ObjectParameter("XML", typeof(string));
    
            var master_IDParameter = master_ID.HasValue ?
                new ObjectParameter("Master_ID", master_ID) :
                new ObjectParameter("Master_ID", typeof(long));
    
            var branch_IDParameter = branch_ID.HasValue ?
                new ObjectParameter("Branch_ID", branch_ID) :
                new ObjectParameter("Branch_ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("POS_OrdersDeltails_save", xMLParameter, master_IDParameter, branch_IDParameter);
        }
    
        public virtual ObjectResult<POS_Pon_Result> POS_Pon(Nullable<long> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<POS_Pon_Result>("POS_Pon", iDParameter);
        }
    }
}
