//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_ShifTypes
    {
        public long ID { get; set; }
        public Nullable<long> Branch_ID { get; set; }
        public Nullable<long> UserCreate { get; set; }
        public Nullable<long> UserLastModified { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string ShifTypeCode { get; set; }
        public string ShifTypeName { get; set; }
        public Nullable<System.DateTime> FromTime { get; set; }
        public Nullable<System.DateTime> ToTime { get; set; }
    }
}
