//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_Kitchens
    {
        public long ID { get; set; }
        public Nullable<long> Branch_ID { get; set; }
        public Nullable<long> UserCreate { get; set; }
        public Nullable<long> UserLastModified { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string KitchenCode { get; set; }
        public string KitchenName { get; set; }
        public string PrinterName { get; set; }
        public Nullable<bool> KitchenHavePrinter { get; set; }
        public Nullable<bool> KitchenHaveScreen { get; set; }
        public string Note { get; set; }
    }
}
