//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class POS_ExpensesTypes
    {
        public long ID { get; set; }
        public Nullable<long> Branch_ID { get; set; }
        public Nullable<long> UserCreate { get; set; }
        public Nullable<long> UserLastModified { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> LastModified { get; set; }
        public string ExpensCode { get; set; }
        public string ExpensName { get; set; }
        public byte[] Image { get; set; }
        public string Note { get; set; }
    }
}
