//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POS
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersPermission
    {
        public long ID { get; set; }
        public Nullable<long> Branch_ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> ScreenID { get; set; }
    }
}
